apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.commonName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Chart.Name }}-certificate
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
  - {{ .Values.certificate.commonName }}