apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.volumes.paperlessmedia.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volumes.paperlessmedia.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: {{ .Release.Namespace }}
     name: {{ .Values.volumes.paperlessmedia.name }}
  hostPath:
    path: {{ .Values.volumes.paperlessmedia.hostpath }}