apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  PAPERLESS_SECRET_KEY: {{ .Values.secret.paperless.PAPERLESS_SECRET_KEY | b64enc }}
  PAPERLESS_ADMIN_USER: {{ .Values.secret.paperless.PAPERLESS_ADMIN_USER | b64enc }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.secret.paperless.PAPERLESS_ADMIN_PASSWORD | b64enc }}
  PAPERLESS_EMAIL_HOST_USER: {{ .Values.secret.paperless.PAPERLESS_EMAIL_HOST_USER | b64enc }}
  PAPERLESS_EMAIL_HOST_PASSWORD: {{ .Values.secret.paperless.PAPERLESS_EMAIL_HOST_PASSWORD | b64enc }}