apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.paperless.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
    - name: {{ .Values.service.paperless.name }}
      port: {{ .Values.service.paperless.port }}
      targetPort: {{ .Values.service.paperless.targetPort }}